//
//  Home Church, the two methods that make push notifications work.
//
//  THIS IS A FRAGMENT, NOT A FILE. Paste both methods inside the existing
//  `class AppDelegate` in ios/App/App/AppDelegate.swift, above its final
//  closing brace. It is kept here rather than as a whole AppDelegate.swift
//  because that file is generated by `npx cap add ios` and its contents
//  change between Capacitor versions; replacing it wholesale would trade this
//  bug for a worse one.
//
//  WHY IT IS NEEDED, and why leaving it out is so hard to diagnose. Capacitor
//  does not see APNs directly. iOS delivers the device token to the app
//  delegate, and @capacitor/push-notifications listens for a NotificationCenter
//  post that only these two methods make. The plugin's own README says to add
//  them and `npx cap add ios` does not, so a project is born without them.
//
//  With them missing, nothing reports anything. iOS registers happily, hands
//  the token to AppDelegate, and AppDelegate drops it. register() resolves
//  normally, the `registration` listener never fires, and `registrationError`
//  never fires either, because there was no error: the token arrived and was
//  thrown away one layer below any JavaScript. Permission reads granted and
//  device_tokens stays empty forever.
//
//  That is the third failure in this feature wearing the same disguise, after
//  the swallowed 403 in js/native.js and the missing aps-environment
//  entitlement. All three present as "no token, no error", and only this one
//  is invisible from inside the web layer entirely. scripts/preflight.js
//  checks for it in ios/ when that directory exists, which is the only place
//  it can be checked, because ios/ is generated and gitignored.
//

func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
}

func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
    NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
}
