#!/usr/bin/env node
/*
 * Home Church, standalone legal pages for the open web.
 *
 * WHY THIS IS NEEDED. Apple requires the privacy policy in two places, and
 * people routinely ship only one. It has to be reachable inside the app,
 * which js/screens/legal.js handles, and it has to be a public URL in the
 * App Store Connect metadata field. A 404 there, or a link to a homepage
 * that never mentions the app, is a 5.1.1 rejection.
 *
 * WHY IT IS GENERATED RATHER THAN WRITTEN TWICE. Two copies of a privacy
 * policy drift, and the drift is invisible until somebody compares them,
 * which is usually a lawyer or a reviewer. js/screens/legal.js is the single
 * source of truth. This renders the same screens in a headless browser,
 * lifts the markup, and wraps it in a page that stands on its own.
 *
 * SELF CONTAINED ON PURPOSE. All CSS is inlined and both typefaces are
 * embedded as base64, so each file is one HTML document with no external
 * requests. Drop it on Squarespace, GitHub Pages, or anywhere else and it
 * renders the same. No relative paths to break.
 *
 * USAGE
 *   npx http-server -p 8770 -s &
 *   node scripts/make_legal_pages.js
 *
 * Writes legal/privacy.html and legal/terms.html.
 * Re-run whenever js/screens/legal.js changes.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.dirname(__dirname);
const BASE = process.env.HC_BASE || 'http://127.0.0.1:8770';
const OUT = path.join(ROOT, 'legal');

const PAGES = [
  { route: 'privacy', file: 'privacy.html', title: 'Privacy policy, Home Church' },
  { route: 'terms',   file: 'terms.html',   title: 'Terms of use, Home Church' }
];

// Only the faces the legal screens actually use. Embedding all six would
// double the file for italics that never appear in a policy.
const FONTS = [
  { family: 'Cormorant', weight: 400, style: 'normal', file: 'cormorant-400.woff2' },
  { family: 'Poppins',   weight: 800, style: 'normal', file: 'poppins-800.woff2' }
];

function read(...parts) {
  return fs.readFileSync(path.join(ROOT, ...parts), 'utf8');
}

function embeddedFonts() {
  return FONTS.map(function (f) {
    const b64 = fs.readFileSync(path.join(ROOT, 'assets', 'fonts', f.file)).toString('base64');
    return `@font-face{font-family:'${f.family}';font-style:${f.style};` +
           `font-weight:${f.weight};font-display:swap;` +
           `src:url(data:font/woff2;base64,${b64}) format('woff2');}`;
  }).join('\n');
}

function shell(title, css, body) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<meta name="robots" content="index,follow">
<!--
  Generated from js/screens/legal.js by scripts/make_legal_pages.js.
  Do not edit this file. Edit the app screen and regenerate, or the two
  copies drift and only a lawyer or a reviewer finds out.
-->
<style>
${css}
</style>
</head>
<body>
<main class="hc-page">
${body}
</main>
</body>
</html>
`;
}

async function main() {
  let chromium;
  try {
    ({ chromium } = require('playwright'));
  } catch (err) {
    try {
      ({ chromium } = require('/opt/node22/lib/node_modules/playwright'));
    } catch (err2) {
      console.error('Playwright not found. npm i -D playwright');
      process.exit(1);
    }
  }

  fs.mkdirSync(OUT, { recursive: true });

  // The app's own stylesheets, minus the ones that only describe app chrome.
  const css = [
    embeddedFonts(),
    read('css', 'tokens.css'),
    read('css', 'base.css'),
    read('css', 'components.css'),
    read('css', 'screens.css'),
    // The app frame is fixed and full bleed, which is right in a web view and
    // wrong on a web page that should just scroll.
    `
/* --- standalone page overrides ------------------------------------------ */
html, body { position: static; overflow: visible; height: auto; }
body { background: var(--hc-paper); }
.hc-page {
  max-width: 46rem;
  margin: 0 auto;
  padding: var(--hc-space-xxl) var(--hc-screen-pad) var(--hc-space-xxxl);
}
/* .hc-screen pads itself to clear the app's fixed header and tab bar, and
   neither exists here. */
.hc-screen { padding-top: 0; padding-bottom: 0; max-width: none; }
.hc-legal a.hc-btn { display: inline-flex; text-decoration: none; }
`
  ].join('\n');

  const browser = await chromium.launch();

  for (const page of PAGES) {
    const p = await browser.newPage();
    await p.goto(`${BASE}/?v=${page.route}`, { waitUntil: 'networkidle' });
    await p.waitForTimeout(400);

    const body = await p.evaluate(() => {
      const view = document.getElementById('hc-view').cloneNode(true);

      // data-action buttons are wired to the app's delegated listener, which
      // does not exist here. Turn the ones that go somewhere into real links
      // and drop the rest, rather than shipping buttons that do nothing.
      view.querySelectorAll('[data-action]').forEach((el) => {
        const url = el.getAttribute('data-url');
        if (el.getAttribute('data-action') === 'open-url' && url) {
          const a = document.createElement('a');
          a.className = el.className;
          a.href = url;
          a.innerHTML = el.innerHTML;
          el.replaceWith(a);
        } else {
          el.remove();
        }
      });

      return view.innerHTML;
    });

    const html = shell(page.title, css, body);
    const file = path.join(OUT, page.file);
    fs.writeFileSync(file, html);
    console.log(`legal/${page.file}  ${(html.length / 1024).toFixed(0)} KB, self contained`);

    await p.close();
  }

  await browser.close();

  fs.writeFileSync(path.join(OUT, 'README.md'),
`# Legal pages for the web

**Generated. Do not edit these by hand.**

They are rendered from \`js/screens/legal.js\`, which is the single source of
truth for this text, so the page on the website and the screen inside the app
cannot say different things. Edit the app screen, then run:

    npx http-server -p 8770 -s &
    node scripts/make_legal_pages.js

Each file is one self contained HTML document. No external requests, no
relative paths, both typefaces embedded. Host them anywhere.

## What they are for

\`privacy.html\` has to be published at a stable public URL and that URL goes
in the **Privacy Policy URL** field in App Store Connect. Apple requires the
policy both in the app and as a public link, and a 404 or a link to a generic
homepage is a Guideline 5.1.1 rejection.

\`terms.html\` is not required by Apple, since the app has no user generated
content and uses Apple's standard EULA. Publish it anyway if there is
somewhere sensible to put it.

## Before publishing

Both are drafts and neither has been read by a lawyer. See \`LAUNCH_TODO.md\`.
`);

  console.log('\nlegal/README.md written. privacy.html is the one that goes in App Store Connect.');
}

main();
