#!/usr/bin/env node
/*
 * Home Church, assemble www/ for Capacitor.
 *
 * WHY THIS EXISTS, given that this repo's whole promise is no build step.
 * It is not a build step. Nothing is compiled, bundled, minified, or
 * transpiled. It is a file copy, and it exists because of one detail of how
 * Capacitor works: `npx cap sync` copies the entire contents of webDir into
 * the iOS app bundle, with no ignore list.
 *
 * The README used to suggest setting webDir to ".", the repo root. That works
 * right up until you run `npm install`, at which point every `cap sync` copies
 * node_modules, the .git directory, the Supabase migrations, the Python
 * scripts, and three process documents into the shipping app. Hundreds of
 * megabytes of things no phone needs, and a handful of them, like the contents
 * of supabase/, that should not be sitting inside a binary anybody can
 * download and unzip.
 *
 * So webDir is www/, and this puts the six things the app actually needs into
 * it. www/ is gitignored, disposable, and regenerated by `npm run sync`.
 *
 * No dependencies. Node's standard library only, which keeps the promise that
 * matters: you can read every line of this project without learning a tool.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.dirname(__dirname);
const OUT = path.join(ROOT, 'www');

// Everything the running app touches, and nothing else. If you add a top
// level file or folder that the app loads at runtime, add it here too, or it
// will work in the browser and 404 on a phone.
const INCLUDE = [
  'index.html',
  'manifest.webmanifest',
  'css',
  'js',
  'assets',
  // The nine practices, generated by scripts/build_practices.js and read at
  // runtime by js/practices.js. Small, static, and the app is wrong without
  // them: leave this out and the Practices grid is empty on a phone while
  // still working perfectly in a browser served from the repo root, which is
  // exactly the kind of bug this list exists to prevent.
  'data'
];

// Inside assets/, these are for people reading the repo, not for the app.
const SKIP_NAMES = new Set(['README.md', '.DS_Store', 'Thumbs.db']);

let files = 0;
let bytes = 0;

function copy(from, to) {
  const stat = fs.statSync(from);

  if (stat.isDirectory()) {
    fs.mkdirSync(to, { recursive: true });
    for (const name of fs.readdirSync(from)) {
      if (SKIP_NAMES.has(name)) continue;
      copy(path.join(from, name), path.join(to, name));
    }
    return;
  }

  fs.copyFileSync(from, to);
  files += 1;
  bytes += stat.size;
}

function main() {
  // Start clean, so a file deleted from the repo does not linger in a stale
  // www/ and keep shipping inside the app.
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  for (const name of INCLUDE) {
    const from = path.join(ROOT, name);
    if (!fs.existsSync(from)) {
      console.error(`sync_web: missing ${name}, expected at the repo root`);
      process.exit(1);
    }
    copy(from, path.join(OUT, name));
  }

  console.log(`www/  ${files} files, ${(bytes / 1024).toFixed(0)} KB`);
  console.log('Next: npx cap sync ios');
}

main();
