-- ===========================================================================
-- Home Church, close the signup trigger's execute grant
--
-- WHAT THIS FIXES. Migration 0009 created public.hc_handle_new_user() and
-- carefully revoked EXECUTE on the other function it added,
-- hc_export_my_data, and then did not do the same here. So the signup trigger
-- function kept Postgres's default grant of EXECUTE to public, which means it
-- is reachable at /rest/v1/rpc/hc_handle_new_user. The Supabase security
-- advisor flags it twice, once for anon and once for authenticated:
--
--   0028_anon_security_definer_function_executable
--   0029_authenticated_security_definer_function_executable
--
-- IS IT ACTUALLY EXPLOITABLE? No, and it is worth saying why rather than
-- fixing it nervously. The function returns `trigger`, and Postgres refuses to
-- call a trigger function directly whatever privileges the caller holds:
--
--   0A000  trigger functions can only be called as triggers
--
-- That check happens before the body runs, so the SECURITY DEFINER context is
-- never entered. The advisor matches on the grant without accounting for the
-- return type. This was probed against the live project rather than assumed.
--
-- SO WHY BOTHER. Because an unexplained security warning sitting on the table
-- that holds member records is exactly the thing you do not want to be
-- explaining during a privacy review, or six months from now to somebody who
-- has to work out from scratch whether it mattered. A clean advisor report is
-- worth more than the argument for leaving it.
--
-- DOES THIS BREAK SIGNUP? No. Postgres checks EXECUTE on a trigger function
-- when the trigger is *created*, not each time it fires.
--
-- APPLIED AND PROVEN, August 12 2026. Both advisor warnings cleared. The ACL
-- went from {=X/postgres, postgres=X, anon=X, authenticated=X, service_role=X}
-- to {postgres=X/postgres, service_role=X/postgres}, and the trigger
-- on_auth_user_created is still enabled.
--
-- HOW IT WAS PROVEN, which is worth writing down because the obvious test does
-- not actually test anything.
--
-- The obvious test is: create a user, check a profiles row appeared. That test
-- is worthless here. Anything with dashboard or MCP access inserts into
-- auth.users as `postgres`, which OWNS this function, so a privilege check
-- could never have blocked it. The test passes whether or not the revoke is
-- safe. It confirms the trigger exists and nothing more.
--
-- The question is also live rather than academic: `supabase_auth_admin`, the
-- role GoTrue actually inserts as during a real signup, held EXECUTE only
-- through the PUBLIC grant this migration removes. After the revoke,
-- has_function_privilege('supabase_auth_admin', ...) returns false. So real
-- signups run through a role that genuinely lacks the grant.
--
-- What settled it: a throwaway replica of this setup was built in its own
-- schema, outside public so PostgREST never saw it, with the same
-- SECURITY DEFINER trigger function and the same revoke. Inserting as
-- `authenticated`, a role confirmed at EXECUTE = false, fired the trigger and
-- wrote the row. That is the claim demonstrated against a role that really
-- does lack the privilege. The probe schema was dropped afterward.
--
-- If this ever needs undoing:
--   grant execute on function public.hc_handle_new_user() to authenticated;
--
-- ON REPLAYING MIGRATIONS. This is recorded in the remote project's migration
-- history as `lock_down_signup_trigger` rather than under this filename. If
-- supabase/migrations/ is ever replayed against this project it will run
-- again, which is harmless: a revoke of an already revoked grant is a no-op.
--
-- HOW TO RUN IT ELSEWHERE
--   Supabase dashboard -> SQL Editor -> New query -> paste -> Run.
--   Safe to run more than once.
-- ===========================================================================

revoke all on function public.hc_handle_new_user() from public, anon, authenticated;

comment on function public.hc_handle_new_user() is
  'Creates the blank profile row alongside every new auth user. EXECUTE is revoked from every client role on purpose, see migration 0011: a trigger function needs no execute grant to fire, and leaving the default grant in place makes it visible at /rest/v1/rpc/ and lights up the security advisor.';
